blog/models.py
from blog import db


class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text(60), nullable=False)

    def __repr__(self):
        return f'Post model( {self.id}, {self.title}, {self.content})'

blog/__init__.py
import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db/blog.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    app.secret_key = os.urandom(36)
    db.init_app(app)

    from blog.main.routes import main

    app.register_blueprint(main)

    return app

blog/main/routes.py
from flask import Blueprint, render_template, request
from blog import db
from blog.models import Post

main = Blueprint('main', __name__)


@main.route('/')
def paginate_posts():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.paginate(page=page, per_page=20)
    if not posts.total >= 100:
        for i in range(1, 101):
            post = Post(title=f'New post', content=f'Я создан автоматически, мой номер {i}')
            db.session.add(post)
        db.session.commit()

    return render_template('index.html', posts=posts)

blog/templates/index.html
{% extends 'layout.html' %}

{% block content%}

<ul>
{% for post in posts.items %}
    <li> {{ post.title }} - {{ post.content }}</li>
{% endfor %}
</ul>


<div class="post_paginate">

    {% for page in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page %}
            {% if posts.page == page %}
                <a class="paginate_link push"> {{ page }}</a>
            {% else %}
                <a class="paginate_link" href="{{ url_for('main.paginate_posts', page=page)}}">{{ page }}</a>

            {% endif %}
        {% else %}
           ...
        {% endif %}
    {% endfor %}
</div>



{% endblock content%}

blog/templates/layout.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Paginate</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
<div class="main">

{% block content %}
{% endblock content %}
</div>
</body>
</html>